# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-23 18:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptomName', models.CharField(max_length=200)),
                ('intensity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('time', models.DateTimeField()),
                ('locLat', models.FloatField()),
                ('locLong', models.FloatField()),
            ],
        ),
    ]
