# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0005_dataextract'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataExtract',
        ),
        migrations.RenameField(
            model_name='symptom',
            old_name='streetaddress',
            new_name='street_address',
        ),
        migrations.RenameField(
            model_name='symptom',
            old_name='symptomName',
            new_name='symptom_name',
        ),
    ]
